ExcluirTela.java

  package com.mycompany.cursosti;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;


public class ExcluirTela extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirTela
     */
    public ExcluirTela() {
        super("Excluir Curso");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdExcluir = new javax.swing.JTextField();
        btnVoltarExcluir = new javax.swing.JButton();
        btnConfirmarExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir cursos");

        jPanel1.setBackground(new java.awt.Color(9, 9, 72));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Curso:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        txtIdExcluir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(txtIdExcluir);
        txtIdExcluir.setBounds(150, 160, 225, 61);

        btnVoltarExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarExcluir.setText("Voltar");
        btnVoltarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarExcluir);
        btnVoltarExcluir.setBounds(40, 360, 88, 46);

        btnConfirmarExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfirmarExcluir.setText("Confirmar");
        btnConfirmarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarExcluir);
        btnConfirmarExcluir.setBounds(390, 360, 92, 46);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnVoltarExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        
        CRUDTela ct = new CRUDTela();
        ct.setVisible(true);
        this.dispose();
        
    }                                                

    private void btnConfirmarExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        int id = Integer.parseInt(txtIdExcluir.getText());
        
        try{
            Cursos cursos = new Cursos(id, " ", " ");
            DAO dao = new DAO();
            dao.excluir(cursos);
            JOptionPane.showMessageDialog(null, "Curso excluido com sucesso!");
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o curso");
        }
    }                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnConfirmarExcluir;
    private javax.swing.JButton btnVoltarExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdExcluir;
    // End of variables declaration                   
}
